### ISSUE TITLE
Type annotations ignored by compilation extension

### ISSUE THREAD

**Issue by omarkad2** [Kiskae/compile-testing-extension#3]
When I use this extension to test my annotation processor, I notice that type annotations are ignored (annotations `TYPE_USE`)
For a given class :
```java
public class TestToParse {

  private @MyAnnotation String field;

}
```
When using `Elements` provided by the extension, I get the right field but `@MyAnnotation` is missing.

**Comment by Kiskae** [comment]
According to [this stackoverflow question](https://stackoverflow.com/questions/55218187/how-to-access-typeuse-annotation-via-annotationprocessor) there is no way to access `TYPE_USE` annotations through the standard annotation processor API.  Any solution to your problem will inherently depend on exactly what you're trying to do and how you're doing it.

**Comment by omarkad2** [comment]
Actually I am not processing type annotations with my processor, but I am trying to access the said annotations using `javax.lang.model.util.Elements`. In fact I succeed when compiling normally, but when I test using your extension with the help of resolved parameters `Elements elements ...` I can't recover type annotations.

For example : 
```java
// Class Processed with my annotation processor
@MyCustomAnnotation
class TestClass {
  private @MyTypeAnnotation String field;
}

@TestInstance(Lifecycle.PER_CLASS)
@ExtendWith({CompilationExtension.class})
class AnnotationProcessorTest {

  @Test
  void test(Elements elements) {
    TypeElement testElement = elements.getTypeElement(TestClass.class.getCanonicalName());
    Element fieldElement =  // Extract Element field from testElement
    fieldElement.asType().getAnnotationMirrors() // returns null
  }
}
```

**Comment by Kiskae** [comment]
Looking at the output in a debugger shows the data is definitely there (when the annotation is `@Retention(RUNTIME)`), but not accessible through the standard api.

By adding the `tools.jar` as a dependency I've been able to use the following code to access the `TYPE_USE` AnnotationMirrors:

```java
import com.sun.tools.javac.code.Symbol;
import com.sun.tools.javac.code.SymbolMetadata;

    List<? extends AnnotationMirror> typeUseAnnotations(Element el) {
        if (el instanceof Symbol) {
            SymbolMetadata meta = ((Symbol) el).getMetadata();
            if (meta != null) {
                return meta.getTypeAttributes();
            }
        }
        return Collections.emptyList();
    }
```

In the end this isn't really a problem with this library since it is a problem any use of the annotation processor runs up against. `TYPE_USE` annotations just don't appear to be a standardized part of the API.

**Comment by omarkad2** [comment]
Thanks, I'm closing the issue
