### ISSUE TITLE
Add to compile-testing

### ISSUE THREAD

**Issue by h908714124** [Kiskae/compile-testing-extension#4]
Hello,
since the original maintainers don't seem to be updating to junit 5 anytime soon.
I have published a fork of compile-testing here:
https://github.com/jbock-java/compile-testing
I have already made a couple of releases on maven central.
For the next release, I am planning to move to junit 5 and would like to add `CompilationExtension`.
Even though I don't fully understand yet what's going on with all that async stuff.
It looks like solid code and seems to work fine.
Would you be willing to contribute to the repo with a PR?

**Comment by h908714124** [comment]
This project depends on google's compile-testing and therefore still pulls JUnit 4.
I would like to add `CompilationExtension` to the fork mentioned above, which will not depend on JUnit 4 anymore.
`CompilationRule` [will be gone](https://github.com/jbock-java/compile-testing/commit/df4e2334920d210c9d8f64c0d3f4de80b96f9f8e) in the next release.
Would you care to make a pull request, or mind if I add `CompilationExtension` myself?

**Comment by h908714124** [comment]
There was no reply, so I went ahead and added it myself. I hope that's OK.

**Comment by Kiskae** [comment]
Apologies for the lack of a reaction, I never ended up being notified about the issue.

I'm honestly fine with you including the code, just make sure that whatever you do complies with the license: compile-testing-extension/blob/master/LICENSE (google's compile-testing code is covered by the same license)
